codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 20%
        threshold: 5%
    patch:
      default:
        target: 20%

comment:
  layout: "files"
  behavior: default
