name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier
        run: npm run prettier:check

      - name: Run tests
        run: npm test

      # Uncomment the following steps if you want to build a Docker container and deploy
      # - name: Build Docker image
      #   run: docker build -t your-image-name .

      # - name: Log in to Docker Hub
      #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # - name: Push Docker image
      #   run: docker push your-image-name

      # - name: Deploy to Heroku
      #   env:
      #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      #   run: |
      #     echo "Deploying to Heroku..."
      #     docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
      #     docker tag your-image-name registry.heroku.com/your-app-name/web
      #     docker push registry.heroku.com/your-app-name/web
      #     heroku container:release web --app your-app-name
